export type Lang = 'el' | 'en';

const el = {
  greetMorning: 'Καλημέρα',
  name: 'Γιώργη',
  today: 'Παρασκευή, 8 Μαΐου',
  mydataSynced: 'myDATA  ·  Συγχρονισμένο',
  mydataAgo: 'Πριν 2 ώρες',
  metricRevenue: 'Έσοδα μήνα',
  metricPending: 'Εκκρεμείς πληρωμές',
  metricNextTax: 'Επόμενη υποχρέωση',
  metricRevenueSub: 'σε σχέση με Απρίλιο',
  pendingSub: 'από 2 τιμολόγια',
  nextTaxSub: 'ΦΠΑ Q2  ·  σε 12 ημέρες',
  recentInvoices: 'Πρόσφατα τιμολόγια',
  viewAll: 'Όλα →',
  paid: 'Πληρώθηκε',
  pending: 'Εκκρεμεί',
  overdue: 'Ληξιπρόθεσμη',
  newInvoice: 'Νέο Τιμολόγιο',
  selectClient: 'Πελάτης',
  selectClientPh: 'Επιλογή πελάτη…',
  description: 'Περιγραφή εργασίας',
  descriptionPh: 'π.χ. Σχεδιασμός λογοτύπου',
  amount: 'Ποσό',
  vat: 'ΦΠΑ',
  date: 'Ημερομηνία τιμολογίου',
  net: 'Καθαρό ποσό',
  total: 'Σύνολο',
  livePreview: 'Ζωντανή προεπισκόπηση',
  sendMydata: 'Αποστολή στο myDATA',
  markHint: 'Το τιμολόγιο θα λάβει MARK αριθμό αυτόματα.',
  taxTitle: 'Φορολογική Εικόνα',
  taxSubtitle: 'Έτος 2025',
  revenueLast6: 'Έσοδα — τελευταίοι 6 μήνες',
  estIncomeTax: 'Εκτιμώμενος φόρος εισοδήματος',
  quarter: 'Q3  ·  Ιούλ–Σεπ',
  efka: 'ΕΦΚΑ εισφορά',
  efkaSub: 'Μηνιαία',
  yearProgress: 'Πρόοδος έτους',
  daysIntoYear: '128 / 365 ημέρες',
  vatAlert: 'Προσοχή: ΦΠΑ απόδοση σε 12 ημέρες',
  vatAlertSub: 'Τρίμηνο Α — λήξη 22 Μαΐου',
  proLockTitle: 'Pro Insights',
  proLockBody: 'Προβλέψεις ταμειακών ροών και βελτιστοποίηση φόρου.',
  proCta: 'Ξεκλείδωσε με Pro',
  expensesTitle: 'Έξοδα',
  photoReceipt: 'Φωτογράφισε απόδειξη',
  photoSub: 'Αυτόματη εξαγωγή με AI',
  manual: 'Καταχώρηση χειροκίνητα',
  catAll: 'Όλα',
  catSoftware: 'Λογισμικό',
  catEquipment: 'Εξοπλισμός',
  catTransport: 'Μεταφορές',
  catOffice: 'Γραφείο',
  catOther: 'Άλλα',
  expensesMonth: 'Σύνολο εξόδων Μαΐου',
  nav1: 'Αρχική',
  nav2: 'Τιμολόγια',
  nav3: 'Φόροι',
  nav4: 'Έξοδα',
  nav5: 'Προφίλ',
};

const en: typeof el = {
  greetMorning: 'Good morning',
  name: 'George',
  today: 'Friday, May 8',
  mydataSynced: 'myDATA  ·  Synced',
  mydataAgo: '2 hours ago',
  metricRevenue: 'Monthly revenue',
  metricPending: 'Outstanding',
  metricNextTax: 'Next obligation',
  metricRevenueSub: 'vs. April',
  pendingSub: 'from 2 invoices',
  nextTaxSub: 'VAT Q2  ·  in 12 days',
  recentInvoices: 'Recent invoices',
  viewAll: 'All →',
  paid: 'Paid',
  pending: 'Pending',
  overdue: 'Overdue',
  newInvoice: 'New invoice',
  selectClient: 'Client',
  selectClientPh: 'Select a client…',
  description: 'Work description',
  descriptionPh: 'e.g. Logo design',
  amount: 'Amount',
  vat: 'VAT',
  date: 'Invoice date',
  net: 'Net amount',
  total: 'Total',
  livePreview: 'Live preview',
  sendMydata: 'Send to myDATA',
  markHint: 'The invoice will receive a MARK number automatically.',
  taxTitle: 'Tax overview',
  taxSubtitle: 'Year 2025',
  revenueLast6: 'Revenue — last 6 months',
  estIncomeTax: 'Estimated income tax',
  quarter: 'Q3  ·  Jul–Sep',
  efka: 'EFKA contribution',
  efkaSub: 'Monthly',
  yearProgress: 'Year progress',
  daysIntoYear: '128 / 365 days',
  vatAlert: 'Heads up: VAT return in 12 days',
  vatAlertSub: 'Q1 — due May 22',
  proLockTitle: 'Pro Insights',
  proLockBody: 'Cash-flow forecasts and tax optimisation.',
  proCta: 'Unlock with Pro',
  expensesTitle: 'Expenses',
  photoReceipt: 'Snap a receipt',
  photoSub: 'AI-extracted automatically',
  manual: 'Enter manually',
  catAll: 'All',
  catSoftware: 'Software',
  catEquipment: 'Equipment',
  catTransport: 'Transport',
  catOffice: 'Office',
  catOther: 'Other',
  expensesMonth: 'May expenses total',
  nav1: 'Home',
  nav2: 'Invoices',
  nav3: 'Tax',
  nav4: 'Expenses',
  nav5: 'Profile',
};

export const STR = { el, en };
export type Strings = typeof el;
