export const C = {
  bg:          '#faf7f1',
  card:        '#ffffff',
  cardSoft:    '#f7f3ea',
  ink:         '#171c19',
  inkSoft:     '#5d6862',
  inkFaint:    '#9aa39d',
  border:      '#ece6d8',
  borderSoft:  '#f1ecde',
  primary:     '#0d5c3a',
  primaryDk:   '#084227',
  primarySoft: '#e3efe6',
  primaryGlow: '#cfe2d4',
  accent:      '#d97757',
  accentSoft:  '#fbece4',
  warning:     '#c7811a',
  warningSoft: '#fbeed0',
  success:     '#1b8a4f',
  successSoft: '#dff1e4',
  danger:      '#b73a32',
  dangerSoft:  '#f8e0dd',
} as const;
